version: 2

updates:
  - package-ecosystem: "uv"
    insecure-external-code-execution: allow
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
      timezone: Asia/Tokyo
