version: 2

updates:
  - package-ecosystem: "uv"
    directories: 
    - "/"
    - "/pipeline"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
      timezone: Asia/Tokyo
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
      timezone: Asia/Tokyo
    groups:
      gha-dependencies:
        patterns:
          - "*"
