[tool.poetry]
name = "sagemaker-pipeline"
version = "0.1.0"
description = "The AWS Sagemaker Pipeline."
authors = ["cuongvd23 <johnvu23.vn@gmail.com>"]
repository = "https://github.com/cuongvd23/sagemaker-pipeline"
keywords = ["aws", "sagemaker", "pipeline", "mlops", "pipecd", "cicd"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
poetry = "1.8.4"

[tool.poetry.group.typing.dependencies]
mypy = "^1.13.0"
types-requests = "^2.32.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
