isLocal: true

regionName: ap-northeast-1
timeZone: Asia/Tokyo

name: pipeline
roleArn: SageMakerRole
s3Bucket: sagemaker-data
s3Prefix: pipelines
s3EndpointUrl: http://172.17.0.1:9000 # docker0 ip addr
mlflowTrackingServerUri: http://172.17.0.1:5000 # docker0 ip addr
mlflowExperimentName: eventscoring-ranking
