isLocal: true

regionName: ap-northeast-1
timeZone: Asia/Tokyo

name: pipeline
roleArn: SageMakerRole
s3Bucket: sagemaker-data
s3Prefix: pipelines
s3EndpointUrl: http://s3:9000 # docker network
mlflowTrackingServerUri: http://mlflow:5000 # docker network
mlflowExperimentName: eventscoring-ranking
